export const GET_CUSTOMERS_LIST_REQUEST = "GET_CUSTOMERS_LIST_REQUEST";
export const GET_CUSTOMERS_LIST_SUCCESS = "GET_CUSTOMERS_LIST_SUCCESS";
export const GET_CUSTOMERS_LIST_ERROR = "GET_CUSTOMERS_LIST_ERROR";

export const GET_CUSTOMER_DETAILS = "GET_CUSTOMER_DETAILS";