export const GET_BOOKLIST_REQUEST = "GET_BOOKLIST_REQUEST";
export const GET_BOOKLIST_SUCCESS = "GET_BOOKLIST_SUCCESS";
export const GET_BOOKLIST_ERROR = "GET_BOOKLIST_ERROR";

export const GET_BOOK_DETAILS = "GET_BOOK_DETAILS";